/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eleks_com_bitmap_resize_app_MainActivity */

#ifndef _Included_eleks_com_bitmap_resize_app_MainActivity
#define _Included_eleks_com_bitmap_resize_app_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eleks_com_bitmap_resize_app_MainActivity
 * Method:    getStringFromFile
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_eleks_com_ndk_begin_app_MainActivity_getStringFromFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     eleks_com_bitmap_resize_app_MainActivity
 * Method:    writeByteArrayToFile
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_eleks_com_ndk_begin_app_MainActivity_writeByteArrayToFile
  (JNIEnv *, jobject, jstring path, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
